### ISSUE TITLE
Decide whether the design of the interaction panels should be service-oriented or unit-oriented

### ISSUE THREAD

**Issue by jdaberkow** [openbase/bco.bcomfy#3]
Can anyone think of specific pros or cons?

Service-oriented would make the interaction look like in dal-visual-remote, whereas the unit-oriented approach is the one, used in bcozy. 

I assume that the service-oriented approach probably needs less time to implement, but is maybe less user focused than the unit-oriented one?

The current approach as seen in the screenshots is service-oriented.

![screenshot_20170519-110717](https://cloud.githubusercontent.com/assets/13017916/26241098/c4d3d28c-3c83-11e7-9085-fa4f3e5381a7.png)
![screenshot_20170519-110757](https://cloud.githubusercontent.com/assets/13017916/26241099/c4d6c71c-3c83-11e7-9426-60d8e2b35de5.png)

**Comment by agatting** [comment]
pro unit-oriented approach: consistency to bcozy interface (usability)

**Comment by TimoMichi** [comment]
pro service-oriented approach: it is more generic and views for new units can be generated just by their services

**Comment by DivineThreepwood** [comment]
The best way would be a mixture out of both approaches. For most units there is just one service most important for controlling. So try to follow the implementation of the simulation mode (and even the future approche of bcozy where I am currently working on).

1. Implement a ServicePane for each ServiceType
2. Implement a GenericUnitPane (extends AbstractCustomUnitPanes) which displays the compatible ServicePanes in a list (e.g. vBox). The compatible Services can be detected by the UnitTemplate. 

After this implementation all Services of each Unit are controllable by the user.
To improve the user usability provide Custom implementation of AbstractCustomUnitPanes (e.g. LightPane) for selected units where the Generic way is to confusing for the user.

Just have a look at the simulation implementation:

1. https://github.com/openbase/bco.dal/tree/master/lib/src/main/java/org/openbase/bco/dal/lib/simulation/unit
2. https://github.com/openbase/bco.dal/tree/master/lib/src/main/java/org/openbase/bco/dal/lib/simulation/service
